name: Build, Deploy, and Sync to Azure DevOps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push container image to Docker Hub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jacoblangevei/lagalt-backend:${{ github.sha }}
        file: ./Lagalt-Backend/Dockerfile

# Deploy to Azure Web App
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Lagalt'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_d9505b0a93a54fb38bfb1afb16d55441 }}
        images: 'index.docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/jacoblangevei/lagalt-backend:${{ github.sha }}'

# Sync to Azure DevOps
  sync:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch the entire history

    - name: Set git user
      run: |
        git config user.email "jacob-langevei@hotmail.com"
        git config user.name "Jacob Langevei"

    - name: Push to Azure DevOps
      run: |
        git remote add azure-devops https://$AZURE_DEVOPS_PAT@dev.azure.com/jacoblangevei/Lagalt/_git/Lagalt
        git push --force azure-devops HEAD:main
      env:
        AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}